/**
 * md.mjs — a deliberately small Markdown dialect.
 *
 * ANYTHING IT DOES NOT UNDERSTAND IS A HARD ERROR, never a silent drop. A page that
 * quietly loses a paragraph still looks fine, which is exactly why it must not be
 * possible. Supported: `##`/`###` headings, paragraphs, `-` and `1.` lists, `>` quotes,
 * `|` pipe tables, `----` rules (four dashes, house style), links, `<https://…>`
 * autolinks, `\[` escapes, **bold**, *italic*, `code`, `::: consider` … `:::`
 * callouts, `@slide <slug>`, `@mymap` and `@canvas`.
 *
 * THE PARAGRAPH IS NOT A FALLBACK. Until 2026-09-26 any line nothing else claimed became
 * a <p>, so a table rendered as six paragraphs of pipes and a numbered list as ten loose
 * paragraphs — with no error, because nothing was dropped. A line that opens like a
 * construct this dialect lacks is now refused rather than printed as its raw syntax.
 *
 * THE CALLOUT NAME IS CHECKED. `::: whatever` is a hard error rather than a div with a
 * class nobody styled — a callout that renders as an unstyled paragraph is the same
 * silent-loss failure as a dropped line, wearing a box.
 */

const ESC = { '&': '&amp;', '<': '&lt;', '>': '&gt;' };

/** Callout name -> the label printed on it. Add a name here AND style it in the CSS. */
const CALLOUTS = new Map([
  ['consider', 'Consider'],
  ['note', 'Note'],
]);

/** Escape text, but leave existing entities (&amp;, &#36;) alone. */
function esc(s) {
  return s.replace(/&(?![a-zA-Z]+;|#\d+;)|[<>]/g, (c) => ESC[c]);
}

/** Backslash escapes, as numeric entities so nothing later reads them as syntax. */
const ESCAPES = { '[': '&#91;', ']': '&#93;', '*': '&#42;', '_': '&#95;', '`': '&#96;', '\\': '&#92;', '|': '&#124;' };

function inline(s, where) {
  let out = esc(s.replace(/\\([[\]*_`\\|])/g, (_, c) => ESCAPES[c]));
  out = out.replace(/`([^`]+)`/g, (_, c) => `<code>${c}</code>`);
  /* `<https://…>` is a link to itself. Matched after esc(), so the angle brackets are
     already &lt; and &gt; and any `&` in the address is already &amp;. */
  out = out.replace(/&lt;(https?:\/\/[^\s]+?)&gt;/g, (_, href) => {
    const ext = !href.includes('monotropicmap.org');
    return `<a href="${href}"${ext ? ' rel="noopener"' : ''}>${href}</a>`;
  });
  out = out.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, (_, t, href) => {
    const ext = /^https?:\/\//.test(href) && !href.includes('monotropicmap.org');
    const rel = ext ? ' rel="noopener"' : '';
    return `<a href="${href}"${rel}>${t}</a>`;
  });
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  out = out.replace(/(^|[^*])\*([^*]+)\*(?!\*)/g, '$1<em>$2</em>');
  if (out.includes('](')) throw new Error(`md: malformed link in ${where}: ${s}`);
  if (/\*\*/.test(out)) throw new Error(`md: unclosed bold in ${where}: ${s}`);
  return out;
}

/** The id a `##`/`###` heading gets, and the only place that rule lives. build.mjs
 *  needs the same ids to point the changelog feed at the entries on the page, and a
 *  second copy of this expression would drift the first time either was touched. */
export function headingId(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

/** `ctx.slides` is a Map of slug -> {src, alt, width, height}, supplied by build.mjs
 *  from slides.mjs and the generated manifest. An `@slide` naming a slug that is not
 *  in it is a hard error: a missing slide must not render as nothing. */
export function render(src, where = 'markdown', ctx = {}) {
  const lines = src.replace(/\r\n/g, '\n').split('\n');
  const out = [];
  let i = 0;
  /* Heading ids already used on this page. A long page can repeat a heading — four
     sections each ending "What Helps" — and four elements sharing one id is a page
     where every link to the third goes to the first. The second becomes -2, and so on. */
  const used = new Map();

  while (i < lines.length) {
    const line = lines[i];

    if (!line.trim()) { i++; continue; }

    if (line === '----') { out.push('<hr>'); i++; continue; }

    if (line.startsWith('@slide ')) {
      const slug = line.slice(7).trim();
      const slides = ctx.slides || new Map();
      const s = slides.get(slug);
      if (!s) {
        throw new Error(`md: @slide "${slug}" is not a known slide (${where}, line ${i + 1}); run tools/make-slides.py, or check tools/slides.mjs`);
      }
      out.push(`<figure class="slide">
  <img src="${s.src}" width="${s.width}" height="${s.height}" loading="lazy" decoding="async" alt="${s.alt.replace(/"/g, '&quot;')}">
</figure>`);
      i++; continue;
    }

    /* `@mymap` drops in the marking tool, generated by build.mjs from areas.mjs so the
       twenty rows cannot drift from the twenty areas. Hard error if the context is
       missing, for the same reason @slide hard-errors: a tool that renders as nothing
       is a page that still looks fine. */
    if (line.trim() === '@mymap') {
      if (!ctx.mymap) {
        throw new Error(`md: @mymap in ${where} (line ${i + 1}) but no tool markup was supplied — build.mjs must pass ctx.mymap`);
      }
      out.push(ctx.mymap);
      i++; continue;
    }

    /* `@canvas` drops in the map builder, generated by build.mjs from shapes.mjs and
       areas.mjs. Hard error when the context is missing, like @mymap and @slide: a
       page that silently renders its tool as nothing still looks fine. */
    if (line.trim() === '@canvas') {
      if (!ctx.canvas) {
        throw new Error(`md: @canvas in ${where} (line ${i + 1}) but no tool markup was supplied — build.mjs must pass ctx.canvas`);
      }
      out.push(ctx.canvas);
      i++; continue;
    }

    if (line.startsWith(':::')) {
      const name = line.slice(3).trim();
      if (!CALLOUTS.has(name)) {
        throw new Error(`md: unknown callout ":::${name}" (${where}, line ${i + 1}); known: ${[...CALLOUTS.keys()].join(', ')}`);
      }
      i++;
      const body = [];
      while (i < lines.length && lines[i].trim() !== ':::') {
        if (lines[i].trim()) body.push(lines[i]);
        i++;
      }
      if (i >= lines.length) throw new Error(`md: callout ":::${name}" is never closed (${where})`);
      i++;
      const inner = body.map((t) => t.startsWith('- ') ? null : `  <p>${inline(t, where)}</p>`);
      const rendered = [];
      let bullets = null;
      for (let k = 0; k < body.length; k++) {
        if (body[k].startsWith('- ')) {
          if (!bullets) { bullets = []; }
          bullets.push(`    <li>${inline(body[k].slice(2), where)}</li>`);
        } else {
          if (bullets) { rendered.push(`  <ul>\n${bullets.join('\n')}\n  </ul>`); bullets = null; }
          rendered.push(inner[k]);
        }
      }
      if (bullets) rendered.push(`  <ul>\n${bullets.join('\n')}\n  </ul>`);
      out.push(`<aside class="callout ${name}">\n  <p class="callout-label">${CALLOUTS.get(name)}</p>\n${rendered.join('\n')}\n</aside>`);
      continue;
    }
    if (/^-{3}$|^-{5,}$/.test(line.trim())) {
      throw new Error(`md: horizontal rules are four dashes in this house (${where}, line ${i + 1})`);
    }

    let m = /^(#{2,3})\s+(.+)$/.exec(line);
    if (m) {
      const level = m[1].length;
      const base = headingId(m[2]);
      const n = (used.get(base) || 0) + 1;
      used.set(base, n);
      const id = n === 1 ? base : `${base}-${n}`;
      out.push(`<h${level} id="${id}">${inline(m[2], where)}</h${level}>`);
      i++; continue;
    }
    if (/^#\s/.test(line)) throw new Error(`md: the h1 comes from the page title, not the body (${where}, line ${i + 1})`);

    /* Constructs this dialect does not have. Each would otherwise fall through to a
       paragraph and print its own syntax. */
    const lacking = [
      [/^#{4,}\s/, 'headings deeper than ### are not supported'],
      [/^- \[[ xX]\]\s/, 'task lists are not supported'],
      [/^[*+]\s/, 'lists use "- ", not "* " or "+ "'],
      [/^\d+\)\s/, 'numbered lists use "1. ", not "1) "'],
      [/^```/, 'code blocks are not supported'],
      [/^<(?!https?:\/\/)[a-zA-Z!/]/, 'raw HTML is not supported'],
    ];
    for (const [re, why] of lacking) {
      if (re.test(line)) throw new Error(`md: ${why} (${where}, line ${i + 1}): ${line}`);
    }

    if (line.startsWith('- ')) {
      const items = [];
      while (i < lines.length && lines[i].startsWith('- ')) { items.push(inline(lines[i].slice(2), where)); i++; }
      out.push(`<ul>\n${items.map((t) => `  <li>${t}</li>`).join('\n')}\n</ul>`);
      continue;
    }

    /* Numbered lists count from one, in order. A list that skips or restarts is almost
       always two lists run together or an item lost in an edit, and <ol> would silently
       renumber it — so the numbers written are checked against the numbers shown. */
    if (/^\d+\.\s/.test(line)) {
      const items = [];
      while (i < lines.length && /^\d+\.\s/.test(lines[i])) {
        const [, num, text] = /^(\d+)\.\s+(.*)$/.exec(lines[i]);
        if (+num !== items.length + 1) throw new Error(`md: numbered list item ${num} should be ${items.length + 1} (${where}, line ${i + 1})`);
        items.push(inline(text, where)); i++;
      }
      out.push(`<ol>\n${items.map((t) => `  <li>${t}</li>`).join('\n')}\n</ol>`);
      continue;
    }

    /* Pipe tables: a header row, a `| --- |` rule, then body rows, every row the same
       width. An empty top-left cell means the first column names its rows, so those
       cells become row headers and the corner is an ordinary empty cell rather than a
       header with no name.
       ON A PHONE THE ROWS STACK. Three columns at 375px either break words mid-way or
       scroll sideways, and both are harder to read than a row heading with each cell
       under its column's name. So every cell carries that name in `data-label` for the
       stylesheet to print. The explicit roles are there because changing a table's
       `display` in CSS strips its table semantics in some browsers; with them, a screen
       reader still hears a table at any width. The wrapper stays focusable and scrolls
       on its own, for a table too wide even for that. */
    if (line.startsWith('|')) {
      const rows = [];
      const start = i;
      while (i < lines.length && lines[i].startsWith('|')) {
        const raw = lines[i].trim();
        if (!raw.endsWith('|')) throw new Error(`md: table row does not end with "|" (${where}, line ${i + 1})`);
        rows.push(raw.slice(1, -1).replace(/\\\|/g, '\u0000').split('|').map((c) => c.replace(/\u0000/g, '\\|').trim()));
        i++;
      }
      if (rows.length < 3 || !rows[1].every((c) => /^:?-{3,}:?$/.test(c))) {
        throw new Error(`md: a table is a header row, a "| --- |" rule and at least one body row (${where}, line ${start + 1})`);
      }
      const width = rows[0].length;
      rows.forEach((r, k) => {
        if (r.length !== width) throw new Error(`md: table row has ${r.length} cells, the header has ${width} (${where}, line ${start + k + 1})`);
      });
      const rowHeads = rows[0][0] === '';
      const names = rows[0].map((c) => inline(c, where).replace(/<[^>]+>/g, '').replace(/"/g, '&quot;'));
      const head = rows[0].map((c, k) => (k === 0 && rowHeads)
        ? '<td role="cell"></td>'
        : `<th scope="col" role="columnheader">${inline(c, where)}</th>`).join('');
      const body = rows.slice(2).map((r) => '    <tr role="row">' + r.map((c, k) => (k === 0 && rowHeads)
        ? `<th scope="row" role="rowheader">${inline(c, where)}</th>`
        : `<td role="cell" data-label="${names[k]}">${inline(c, where)}</td>`).join('') + '</tr>').join('\n');
      const label = names.filter(Boolean).join(', ');
      out.push(`<div class="tablewrap" role="region" aria-label="Table: ${label}" tabindex="0">\n<table role="table">\n  <thead role="rowgroup">\n    <tr role="row">${head}</tr>\n  </thead>\n  <tbody role="rowgroup">\n${body}\n  </tbody>\n</table>\n</div>`);
      continue;
    }

    if (line.startsWith('> ')) {
      const body = [];
      while (i < lines.length && lines[i].startsWith('> ')) { body.push(inline(lines[i].slice(2), where)); i++; }
      const cite = body.length > 1 && body[body.length - 1].startsWith('— ')
        ? body.pop().slice(2) : null;
      out.push(
        `<blockquote>\n${body.map((t) => `  <p>${t}</p>`).join('\n')}` +
        (cite ? `\n  <cite>${cite}</cite>` : '') + `\n</blockquote>`
      );
      continue;
    }

    if (/^\s+\S/.test(line)) throw new Error(`md: unexpected indent (${where}, line ${i + 1}): ${line}`);

    out.push(`<p>${inline(line, where)}</p>`);
    i++;
  }
  return out.join('\n');
}
