/**
 * slides.mjs — the sixteen slides of the training deck.
 *
 * AUTHORED. `page` is the page of *Training: Map of Monotropic Experiences with
 * presenter notes* the slide is rendered from; ten of the PDF's 26 pages are notes
 * continuations and carry no slide. `alt` is written by hand, because alt text is
 * content — it is the slide for anyone who cannot see it, and it must be reviewable
 * in one place rather than scattered through the prose.
 *
 * The slide IMAGES are generated by `tools/make-slides.py` and their dimensions live
 * in the generated `images/slides/manifest.json`. Never hand-edit either.
 *
 * THE SOURCE PDF IS NOT IN THIS REPOSITORY. It is 62 MB and it is published by
 * Autistic Realms; `make-slides.py` fetches it. A regeneration therefore needs the
 * network, and `--check` says so rather than reporting a pass it did not earn.
 */
export const SLIDE_PDF =
  'https://autisticrealms.com/wp-content/uploads/2025/05/Training-Map-of-Monotropic-Experiences-with-presenter-notes.pdf';

export const SLIDES = [
  { page: 1, slug: 'title',
    alt: 'Title slide. "Map of Monotropic Experiences: Reframing Autism Through A Neurodiversity-Affirming Lens." Created by Helen Edgar (Autistic Realms) and Ryan Boren, Norah Hobbs and Chelsea Adams (Stimpunks). Free training for professionals, families and community groups to support Autistic people. An illustrated landscape of tents, a campfire, trees, mountains and a river under a large sun.' },
  { page: 3, slug: 'not-a-disorder',
    alt: 'A slide reading "Autism is not a disorder. Being Autistic is a difference in neurology." Below the text is the rainbow infinity symbol of the neurodiversity movement.' },
  { page: 4, slug: 'learning-objectives',
    alt: 'Learning objectives, beside a small copy of the Map of Monotropic Experiences. One, understanding the difficulties of neuronormative domination. Two, understanding monotropism and stuck states. Three, understanding monotropism and flow states. Four, understanding monotropic socialising and the importance of the environment.' },
  { page: 5, slug: 'neurodiversity-paradigm',
    alt: 'Three panels comparing models. Medical Model: fix or cure the person, try to change the person so they fit into society’s norms and expectations. Social Model: adapt the environment to meet needs, change society’s attitude and policy so everyone is included. Neurodiversity Paradigm: rejects the medical model and embraces the idea that everyone is unique and has different needs; there is no normal way of being; neurodivergence is part of the celebration of a naturally diverse society; striving for equity.' },
  { page: 6, slug: 'two-maps',
    alt: 'The two maps side by side. On the left, Autism &amp; The Map of Neuronormative Domination — an island with a grey highway, a shark, a warning triangle and the Marsh of Masking. On the right, the title "Autism &amp; The Map of Neuronormative Domination versus The Map of Monotropic Experiences".' },
  { page: 8, slug: 'paradigm-shift',
    alt: 'A slide reading "Let’s Embrace the Neurodiversity Paradigm Shift. Monotropism is Neurodiversity Affirming and Validates Inner Experiences", over an illustrated landscape of hills and trees.' },
  { page: 10, slug: 'what-is-monotropism',
    alt: 'A slide titled "What is Monotropism?" carrying the community definition: monotropism is a neurodiversity affirming theory of autism (Murray et al 2005); Autistic, ADHD and AuDHD people are more likely to be monotropic (Garau et al., 2023); monotropic people have an interest based nervous system, focusing more attention resources on fewer things at any one time than people who may be polytropic; things outside an attention tunnel may get missed and moving between attention tunnels can be difficult and take a lot of energy. A note credits community input gathered across social media in January 2024.' },
  { page: 12, slug: 'intersectionality',
    alt: 'A slide titled "Intersectionality &amp; The Double Empathy Problem". On the left, the Wheel of Power and Privilege by Sylvia Duckworth, a coloured wheel with "power" at the centre and "marginalized" at the rim, segmented by skin colour, citizenship, formal education, ability, sexuality, mental health, body size, housing, wealth, language and gender. On the right, a note that Kimberlé Crenshaw is a Black feminist legal scholar who first coined the term intersectionality in her essays of 1989 and 1991.' },
  { page: 14, slug: 'map-with-key',
    alt: 'The Map of Monotropic Experiences shown beside a numbered key listing all twenty areas, from Attention Tunneling through to Sudden Storms of Unexpected Events. The key credits the map as created by Helen Edgar, Autistic Realms, October 2024, and lists its inspirations.' },
  { page: 16, slug: 'difficulties',
    alt: 'A slide titled "Difficulties of Neuronormative Domination", showing three areas of the map: Shark Infested Waters (13), Cyclones of Unmet Needs (5), and Burnout Whirlpools (15), illustrated with sharks in a rough sea, a tornado, and a whirlpool.' },
  { page: 18, slug: 'stuck-states',
    alt: 'A slide titled "Monotropism: Stuck States", showing seven areas of the map: Mountains of ruminating thoughts (4), Sudden Storms of Unexpected Events (20), Panic Hills of Low-Object Permanence (16), Burnout Whirlpools (15), Lake of Limerence (18), Tides of the Sensory Sea (19), and Meerkat Mounds (11).' },
  { page: 20, slug: 'flow-states',
    alt: 'A slide titled "Monotropism: Flow States", showing seven areas of the map: Infodump Canyon (7), Tendril Theory (3), Attention Tunnels (1), Rabbit Holes of Research (6), River of monotropic flow states (9), Riverbanks of Monotropic Time (12), and Tides of the Sensory Sea (19), under a bright sun.' },
  { page: 22, slug: 'monotropic-socialising',
    alt: 'A slide titled "Monotropic Socializing &amp; Importance of Environment", showing five areas of the map: Forest of Joy Awe and Wonder (17), Rhizomatic Communities (8), Beach of Body Doubling (15), Penguin Pebbling Cove of Friendship (2), and Campsite of Cavendish Spaces (10), illustrated with penguins, a beach, tents and trees.' },
  { page: 24, slug: 'further-ideas',
    alt: 'A slide headed "Further ideas to use the map", asking: where are you on the map? Where do you want to be? How can you get there? What support will you need? What is your biggest hurdle? It closes with an invitation to share your story.' },
  { page: 25, slug: 'questions',
    alt: 'A slide reading simply "Q&amp;A", over an illustration of mountains, a tent and the sun — open space for questions and discussion.' },
  { page: 26, slug: 'find-out-more',
    alt: 'Closing slide, "Find out More!", listing autisticrealms.com, stimpunks.org and monotropism.org, inviting you to purchase a poster of the Map of Monotropic Experiences in the Stimpunks shop and to donate to Stimpunks and support the community. The map is shown alongside.' },
];

export function validate() {
  const problems = [];
  const seen = new Set();
  for (const s of SLIDES) {
    if (seen.has(s.slug)) problems.push(`duplicate slide slug: ${s.slug}`);
    seen.add(s.slug);
    if (!Number.isInteger(s.page) || s.page < 1 || s.page > 26) problems.push(`${s.slug}: page ${s.page} is not in the 26-page PDF`);
    /* Alt text is the slide for anyone who cannot see it. A short one is a slide
       thrown away, so the floor is deliberately high. */
    if (!s.alt || s.alt.length < 80) problems.push(`${s.slug}: alt text is too thin to stand in for the slide`);
  }
  return problems;
}
